name: env_twiss
channels:
  - stanfordnlp
  - ralexx
  - cogsci
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - pip=21.2.4
  - black
  - dask[dataframe]>=2.9.0
  - distributed>=2.11.0
  - flake8
  - isort
  - jupyter
  - jupyterlab
  - matplotlib-base
  - numpy>=1.15.1
  - openpyxl
  - pandas>=0.25.0
  - patsy>=0.4.1
  - PyYAML
  - requests>=2.9.1
  - scikit-learn>=0.22.0
  - scipy>=1.2.0
  - seaborn
  - statsmodels>=0.9.0
  - stumpy>=1.7.2
  - tqdm>=4.10.0
# pip install git+https://github.com/nelsoncardenas/tsfresh.git
